services:
  website-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: website-dev
    restart: always
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev
  website-prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: website-prod
    restart: always
    ports:
      - 3000:3000
    profiles:
      - prod
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
